### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by joshuajabbour** [StackStorm/st2packaging-dockerfiles#16]
It seems like this repo isn't kept very up-to-date. Besides the readme containing links to quay.io, I get the following errors:

```
st2-dockerfiles $ docker-compose up -d
Building data
Step 1 : FROM st2
Pulling repository docker.io/library/st2
ERROR: Service 'data' failed to build: Error: image library/st2 not found
```

**Comment by mccricardo** [comment]
There's another one missing: st2garbagecollector.

I build them locally docker-compose was able to finish.

<img width="655" alt="screen shot 2016-08-05 at 18 04 10" src="https://cloud.githubusercontent.com/assets/1016505/17444521/47695ea2-5b38-11e6-8475-096e9dd283fb.png">

<img width="665" alt="screen shot 2016-08-05 at 18 11 23" src="https://cloud.githubusercontent.com/assets/1016505/17444520/476661e8-5b38-11e6-83f0-49581c789e70.png">
