### ISSUE TITLE
Client and data containers failed on `docker-compose up`

### ISSUE THREAD

**Issue by armab** [StackStorm/st2packaging-dockerfiles#21]
As reported in https://github.com/StackStorm/st2-dockerfiles/issues/16#issuecomment-237907926 by @mccricardo
![](https://cloud.githubusercontent.com/assets/1016505/17444521/47695ea2-5b38-11e6-8475-096e9dd283fb.png) 

[`client`](https://github.com/StackStorm/st2-dockerfiles/blob/master/client/Dockerfile) and [`data`](https://github.com/StackStorm/st2-dockerfiles/tree/master/data) records in [`docker-compose.yml`](https://github.com/StackStorm/st2-dockerfiles/blob/f4a43a05d3cc6cea49a7b16945163c117e314dd2/docker-compose.yml#L96-L111) are trying to build an image from the `st2`, which is not available in Docker Hub. That leads to error, because `st2` "temporary" image is used only for internal build stage.

User should care only about running `docker-compose up`, without having any issues.

**Comment by cgrigor** [comment]
Any news on this? Getting the same.... :-(
docker-compose up -d
st2dockerfiles_mongo_1 is up-to-date
st2dockerfiles_rabbitmq_1 is up-to-date
Building data
Step 1 : FROM st2
Pulling repository docker.io/library/st2
ERROR: Service 'data' failed to build: Error: image library/st2:latest not found

**Comment by armab** [comment]
Sorry, @cgrigor no update on this.
For the moment Docker is officially unsupported, but there are plans to bring more focus on this installation way of StackStorm (no ETA yet).

As a workaround, you can do the following steps from this https://github.com/StackStorm/st2-dockerfiles/pull/19#issuecomment-237922709: 
```
git clone https://github.com/StackStorm/st2-dockerfiles.git

# build "base" `st2` image
# replace ST2_VERSION if needed: 
docker build --build-arg ST2_VERSION="1.6.0-2" --build-arg ST2_REPO="staging-stable" -t st2 stackstorm/

# build service containers manually from the "base"
CONTAINERS="st2actionrunner st2api st2auth st2stream st2exporter st2notifier st2resultstracker st2rulesengine st2sensorcontainer st2garbagecollector"

for container in $CONTAINERS; do
  docker build -t stackstorm/${container}:latest ${container}
done
```

After that, you can use it (example):
```sh
docker-compose up -d

# show st2 version
docker-compose run client st2 --version

# list packs
docker-compose run client st2 action list --pack=core

# install github pack
docker-compose run client st2 run packs.install packs=github
```

**Comment by cgrigor** [comment]
Nice one, thanks.

**Comment by armab** [comment]
TODO: Consider deploying to Docker Hub `st2base` image (which is parent for all other images).

This will guarantee smooth `docker-compose up`.
