### ISSUE TITLE
Consider moving to ubuntu:14.04 as base image

### ISSUE THREAD

**Issue by armab** [StackStorm/st2packaging-dockerfiles#23]
> Reported in https://github.com/StackStorm/st2-dockerfiles/pull/18

Currently `Debian Wheezy` base docker image is used because of the small image size: 
- [`debian:wheezy`](https://hub.docker.com/r/library/debian/tags/) - `37MB`

As @code-ape catched, looks like `ubuntu:14.04` slightely minimized their base container size pretty dramatically. That could be a good argument for switching to ubuntu14, since the diff is not that big now:
- [`ubuntu:14.04`](https://hub.docker.com/r/library/ubuntu/tags/) - now `66MB` (before it was `200+`MB)

TODO:
Compare final image size after full st2 build/install, provide stats here and decide.

> Even more. If done, it looks like there is no reason (?) to build `Debian Wheezy` via https://github.com/stackstorm/st2-packages anymore

**Comment by mccricardo** [comment]
Why not [alpine](https://hub.docker.com/_/alpine/)?

**Comment by armab** [comment]
Alpine Linux is not a Debian derivate, so it does not support `.deb` or `.rpm` packages we build.

**Comment by mccricardo** [comment]
Makes sense. Still looking around superficially. Lot of stuff I don't know.
