### ISSUE TITLE
Build st2 base image with ST2_VERSION="2.2.1-4"

### ISSUE THREAD

**Issue by herveleclerc** [StackStorm/st2packaging-dockerfiles#49]
Error when building st2 base image with command : docker build --build-arg ST2_VERSION="2.2.1-4" --build-arg ST2_REPO="staging-stable" -t st2 stackstorm/

Missing package in Dockerfile : openssh-server

Build Error :
st2 depends on openssh-server; however:
  Package openssh-server is not installed

fix simply add openssh-server in apt-get section in dockerfile

**Comment by armab** [comment]
@herveleclerc Thanks for the report! :+1: 

Talking about the StackStorm docker containers. Just a note that this repository is outdated and supported by community efforts only, so it's not "official".

Recently we've started planning and thinking on dockerizing stackstorm internally with 2 solutions:
- `all st2 components in one container` for some simple use cases: https://github.com/StackStorm/st2-docker/pull/1
- `multiple containers, 1 st2 service per image` for prod: similar approach is https://gitlab.com/smithx10/st2/blob/master/docker-compose.yml

If interested to leave your feedback, - your opinion will be very welcome as early adopter. Please join our Slack Community https://stackstorm.com/community-signup and dedicated `#docker` channel where we started gathering feedback. What would you like to see as a potential StackStorm + Docker user, what are the use cases?
